services:
  web_app:
    build: .
    command:  python Homework_LAST_.py
    ports:
      - 5001:5001
    environment:
      - RABBITMQ_HOST=rabbit_host

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbit_host

  celery_worker:
    build: .
    command: celery -A celery_tasks worker --loglevel=INFO --purge --pool=solo
    environment:
      - RABBITMQ_HOST=rabbit_host
